title = "A FOF"
description = "按权重组合虚拟基金"
frequency = "3m"

[funds]
high-dividend = 2
high-momentum = 5
permanent = 1
strong-small-cap = 2

[search]
frequency = ["3m", "6m", "1y"]

[search.funds]
high-dividend = [1, 2, 3, 5]
high-momentum = [1, 2, 3, 5]
permanent = [1, 2, 3, 5]
strong-small-cap = [1, 2, 3, 5]
