title = "A FOF"
description = "基金按权重进行组合"

[funds]
# conv-bond = 1
high-dividend = 2
# high-momentum-sharpe = 3
permanent = 1
# strong-small-cap = 3

# 交叉验证偏重夏普，指定参数 -A 0.3
[search]
# conv-bond = [1, 2, 3]
high-dividend = [1, 2, 3]
# high-momentum-sharpe = [1, 2, 3]
permanent = [1, 2, 3]
# strong-small-cap = [1, 2, 3]
