title = "A FOF"
description = "基金按权重进行组合"

[funds]
conv-bond = 1
high-dividend = 1
high-momentum-sharpe = 1
risk-parity = 1

[search]
conv-bond = [1, 2, 3]
high-dividend = [1, 2, 3]
high-momentum-sharpe = [1, 2, 3]
risk-parity = [1, 2, 3]
