title = "高性价比可转债"
description = "持有满足一定条件且最有性价比的可转债"

[[rules]]
name = "hold_by_conv_bond_premium"
frequency = "2m"
frequency_take_profit_pct = 0

[rules.options]
issue_size_quantile_lower = 0.2
limit = 3
min_remaining_days = 180
remain_lower = 0.8
straight_premium_quantile_upper = 0.8
weight_exp = 0

[rules.search]
frequency = ["1w", "2w", "1m", "2m", "3m", "4m", "6m"]
# frequency_take_profit_pct = [0, 5, 10, 15, 20, 25, 30, 40, 50]
issue_size_quantile_lower = [0, 0.1, 0.2, 0.3, 0.4, 0.5]
# limit = [2, 3, 4, 5, 10, 20]
# min_remaining_days = [30, 60, 90, 180, 360]
# remain_lower = [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
# straight_premium_quantile_upper = [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
# weight_exp = [0, 0.25, 0.5, 1.0, 2.0, 4.0]
