title = "多因子评分"
description = "持有多因子评分最高的ETF"

tickers = [
  "510300", # 沪深300ETF
  "159338", # 中证A500ETF
  "510500", # 中证500ETF
  "159949", # 创业板50ETF
  "510900", # 恒生H股ETF
  "512090", # MSCI中国A股ETF
  "515180", # 中证红利ETF
  "513100", # 纳斯达克100ETF
  "513500", # 标普500ETF
  "518880", # 黄金ETF
  "511260", # 十年国债ETF
  "511180", # 可转债ETF
  "516650", # 有色金属ETF
  "162411", # 华宝油气LOF
  "159985", # 豆粕期货ETF
]

[[rules]]
name = "hold_top_factors_score"
frequency = "6m"

[rules.options]
limit = 2
lookback_trade_days = 126
rebalance_with_indicator = true
weight_max_drawdown = 0
weight_momentum = 1
weight_sharpe = 1
weight_volatility = 0

[rules.search]
frequency = ["1w", "2w", "1m", "3m", "6m", "9m", "1y"]
limit = [2, 3, 4, 5]
lookback_trade_days = [21, 63, 126, 189, 252]
rebalance_with_indicator = [true, false]
# weight_max_drawdown = [0, 1, 2]
# weight_momentum = [0, 1, 2]
# weight_sharpe = [0, 1, 2]
# weight_volatility = [0, 1, 2]
