title = "多因子提升"
description = "基于对多个因子进行组合提升学习后从国证300中选择股票并持有"

[[ticker_sources]]
source = "399312.CNI"
source_type = "index"

[[rules]]
name = "hold_by_factors_boosting"
frequency = "1m"

[rules.options]
bbands_multiplier = 2
bbands_period = 20
limit = 2
metric_r2_threshold = 0.9
rsi_period = 14
score_arr_weight = 1.0
skip_same_sector = false
step_trade_days = 42
steps = 10
xgboost_gamma = 1
xgboost_lambda = 1
xgboost_learning_rate = 0.4
xgboost_max_depth = 5
xgboost_min_child_weight = 1
xgboost_n_estimators = 100

[rules.search]
# frequency = ["1w", "2w", "1m", "3m", "6m", "9m", "1y"]

[rules.search.options]
# limit = [1, 2, 3, 4, 5]
# metric_r2_threshold = [0.0, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]
# score_arr_weight = [0.0, 0.4, 0.5, 0.6, 1.0]
# skip_same_sector = [true, false]
step_trade_days = [5, 10, 21, 31, 42]
# steps = [10, 20, 30]
# xgboost_gamma = [0, 0.1, 1, 2]
# xgboost_lambda = [0.1, 1, 5, 10]
xgboost_learning_rate = [0.3, 0.4, 0.5]
xgboost_max_depth = [3, 4, 5, 6]
# xgboost_min_child_weight = [1, 3, 5]
xgboost_n_estimators = [50, 100, 150, 200]
