title = "高股息"
description = "持有中证A500中股息率最高的股票"

[[ticker_sources]]
source = "000510.CSI"
source_type = "index"

[[rules]]
name = "hold_top_dividend"
frequency = "1y"

[rules.options]
filter_roe_floor = 0.01
limit = 5
lookback_years = 3
skip_same_sector = false

[rules.search]
frequency = ["3m", "6m", "1y"]
filter_roe_floor = [0.0, 0.01, 0.02, 0.04]
limit = [3, 5, 10]
lookback_years = [2, 3, 4]
skip_same_sector = [true, false]
