title = "高收益PX比"
description = "持有国证300中全收益与PE/PS/PB比值最高的股票"

[[ticker_sources]]
source = "399312.CNI"
source_type = "index"

[[rules]]
name = "hold_by_return_px_ratio"
frequency = "1y"

[rules.options]
limit = 3
lookback_years = 2
min_trade_days = 126
px = "pe"
skip_same_sector = true
weight_exp = 1

[rules.search]
frequency = ["6m", "1y", "18m", "2y"]
limit = [3, 4, 5, 10]
lookback_years = [1, 2, 3]
min_trade_days = [21, 63, 126]
px = ["pe", "ps", "pb"]
skip_same_sector = [true, false]
weight_exp = [0, 0.25, 0.5, 1.0, 2.0, 4.0]
