title = "高稳定性"
description = "持有国证300中市值大、换手率低、股价波动小的股票"

[[ticker_sources]]
source = "399312.CNI"
source_type = "index"

[[rules]]
name = "hold_by_stablity"
frequency = "3w"

[rules.options]
enable_indicator_weighting = false
limit = 3
lookback_trade_days = 126
skip_same_sector = false
weight_market_cap = 1
weight_turnover_ratio = 2
weight_volatility = 3

[rules.search]
frequency = ["1w", "2w", "3w", "1m", "3m", "6m", "9m", "1y"]
# enable_indicator_weighting = [true, false]
limit = [3, 4, 5, 10]
# lookback_trade_days = [21, 63, 126, 189, 252]
# skip_same_sector = [true, false]
# weight_market_cap = [0, 1, 2, 3, 5]
# weight_turnover_ratio = [0, 1, 2, 3, 5]
# weight_volatility = [0, 1, 2, 3, 5]
