title = "高股息"
description = "持有国证300中股息率最高的股票"

[[ticker_sources]]
source = "399312.CNI"
source_type = "index"

[[rules]]
name = "hold_by_dividend"
frequency = "1y"

[rules.options]
div_allot_weight = -0.5
div_bonus_gift_weight = -1
limit = 3
lookback_div_years = 4
lookback_trade_days = 252
min_div_count_per_year = 0.8
price_avg_count = 5
skip_same_sector = false
volatility_quantile_upper = 0.5
weight_exp = 0

[rules.search]
# frequency = ["3m", "6m", "9m", "1y", "18m", "2y"]
# div_allot_weight = [-1, -0.5, 0, 0.5, 1]
# div_bonus_gift_weight = [-1, -0.5, 0, 0.5, 1]
# limit = [3, 4, 5, 10]
# lookback_div_years = [3, 4, 5]
lookback_trade_days = [21, 42, 63, 84, 126, 189, 252]
# min_div_count_per_year = [0.6, 0.8, 1, 1.2, 1.4]
# price_avg_count = [1, 3, 5, 10, 20]
# skip_same_sector = [true, false]
volatility_quantile_upper = [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
# weight_exp = [0, 0.25, 0.5, 1, 2, 4]
