title = "高股息"
description = "持有红利指数中股息率最高的股票"

[[ticker_sources]]
source = "000015.CSI"  # 上证红利
source_type = "index"

[[ticker_sources]]
source = "000922.CSI"  # 中证红利100
source_type = "index"

[[ticker_sources]]
source = "399324.CNI"  # 深证红利
source_type = "index"

[[ticker_sources]]
source = "399411.CNI"  # 国证红利100
source_type = "index"

[[rules]]
name = "hold_by_dividend"
frequency = "6m"

[rules.options]
arr_quantile_lower = 0.3
div_allot_weight = 0
div_bonus_gift_weight = 0.25
div_weight_yearly_decay = 0.3
limit = 2
lookback_div_years = 3
lookback_trade_days = 750
min_div_count_per_year = 0.8
price_avg_count = 5
skip_same_sector = false
volatility_quantile_upper = 0.3
weight_method = "filter_max(0.9)"

[rules.search]
# frequency = ["6m", "1y", "18m", "2y", "3y"]

[rules.search.options]
arr_quantile_lower = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
# div_allot_weight = [-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1]
# div_bonus_gift_weight = [-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1]
# div_weight_yearly_decay = [-0.2, -0.1, 0, 0.1, 0.2, 0.3]
# limit = [2, 3, 4, 5, 10]
# lookback_trade_days = [250, 500, 750, 1000, 1250]
# lookback_div_years = [1, 2, 3, 4, 5]
# min_div_count_per_year = [0.6, 0.8, 1, 1.2, 1.4]
# skip_same_sector = [true, false]
volatility_quantile_upper = [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
# weight_method = [
#   "equal",
#   "filter_max(0.9)",
#   "filter_max(0.8)",
#   "filter_max(0.7)",
#   "filter_max(0.6)",
#   "filter_max(0.5)",
# ]
