title = "高稳定性"
description = "持有国证300中市值大、换手率低、股价波动小的股票"

[[ticker_sources]]
source = "399312.CNI"
source_type = "index"

[[rules]]
name = "hold_by_stablity"
frequency = "1m"

[rules.options]
factor_market_cap_weight = 1
factor_turnover_ratio_weight = 5
factor_volatility_weight = 2
limit = 3
lookback_trade_days = 125
skip_same_sector = false
weight_method = "equal"

[rules.search]
# frequency = ["1m", "2m", "3m", "6m", "9m", "1y"]

[rules.search.options]
# factor_market_cap_weight = [0, 1, 2, 3, 5]
# factor_turnover_ratio_weight = [0, 1, 2, 3, 5]
# factor_volatility_weight = [0, 1, 2, 3, 5]
# limit = [2, 3, 4, 5, 10]
# lookback_trade_days = [21, 63, 125, 188, 250]
# skip_same_sector = [true, false]
