title = "简易永久组合"
description = "按固定比例持有股票、债券、黄金"

[tickers]
"515450" = 7.5  # 红利低波50ETF
"159949" = 7.5  # 创业板50ETF
"513100" = 7.5  # 纳斯达克100ETF
"513500" = 7.5  # 标普500ETF
"511260" = 50  # 十年国债ETF，实际操作可在利率走高时将小部分长期国债置换为短期国债/货币/短融
"518880" = 20  # 黄金ETF

[[rules]]
name = "hold"
frequency = "1y"

[rules.search]
frequency = ["3m", "6m", "1y", "2y"]

[[rules]]
name = "resize_by_index_valuation"
frequency = "1w"

[rules.options]
allow_short = false
lookback_years = 6
pb_quantile_lower = 0.1
pb_quantile_upper = 0.95
pe_quantile_lower = 0.1
pe_quantile_upper = 0.95
ticker_watch_index = { "159949" = "399006.SZ" }

# [rules.search.options]
# lookback_years = [5, 6, 7, 8, 10, 12]
# pb_quantile_lower = [0.1, 0.2, 0.3, 0.4]
# pb_quantile_upper = [0.8, 0.9, 0.95]
# pe_quantile_lower = [0.1, 0.2, 0.3, 0.4]
# pe_quantile_upper = [0.8, 0.9, 0.95]
