title = "风险平价"
description = "根据风险平价理论对持有的股票、债券、黄金进行动态调仓"

[tickers]
"515450" = 2.5 # 红利低波50ETF
"159949" = 2.5 # 创业板50ETF
"513100" = 2.5 # 纳斯达克100ETF
"513500" = 2.5 # 标普500ETF
"511260" = 10  # 十年国债ETF
"518880" = 10  # 黄金ETF

[[rules]]
name = "hold_by_risk_parity"
frequency = "1m"

[rules.options]
lookback_trade_days = 21
max_weight_scale = 2
min_weight_scale = 0.25

[rules.search]
frequency = ["1m", "2m", "3m", "6m", "1y"]
lookback_trade_days = [21, 42, 63, 126, 189, 252]
max_weight_scale = [2, 4, 8, 16]
min_weight_scale = [0, 0.125, 0.25, 0.5]
