title = "估值安全"
description = "根据指数估值高低对持有的资产进行动态调仓"

[tickers]
# "510300" = 10  # 沪深300ETF
"159949" = 10  # 创业板50ETF

[[rules]]
name = "hold"
frequency = "1y"

[[rules]]
name = "resize_by_index_valuation"
frequency = "1w"

[rules.options]
allow_short = false
lookback_years = 10
pb_quantile_lower = 0.1
pb_quantile_upper = 0.95
pe_quantile_lower = 0.4
pe_quantile_upper = 0.95
ticker_watch_index = { "510300" = "000001.SH", "159949" = "399006.SZ" }

[rules.search.options]
# allow_short = [true, false]
# lookback_years = [8, 10, 12]
pb_quantile_lower = [0.1, 0.2, 0.3, 0.4]
pb_quantile_upper = [0.8, 0.9, 0.95]
pe_quantile_lower = [0.1, 0.2, 0.3, 0.4]
pe_quantile_upper = [0.8, 0.9, 0.95]
