title = "趋势增强"
description = "持有趋势增强得分最高的ETF"

tickers = [
  "510300", # 沪深300ETF
  "159338", # 中证A500ETF
  "510500", # 中证500ETF
  "159949", # 创业板50ETF
  "510900", # 恒生H股ETF
  "512090", # MSCI中国A股ETF
  "515180", # 中证红利ETF
  "515450", # 红利低波50ETF
  "513100", # 纳斯达克100ETF
  "513500", # 标普500ETF
  "518880", # 黄金ETF
  "511260", # 十年国债ETF
  "511180", # 可转债ETF
  "516650", # 有色金属ETF
  "162411", # 华宝油气LOF
  "159985", # 豆粕期货ETF
]

[[rules]]
name = "hold_by_trend"
frequency = "3m"

[rules.options]
limit = 1
lookback_trade_days = 63
ma_exp = 0
ma_period_fast = 5
ma_period_slow = 20
metric_r2_threshold = 0.7
regression_alpha = 8
weight_exp = 0.0

[rules.search]
# frequency = ["1w", "2w", "3w", "1m", "2m", "3m", "4m"]
# limit = [1, 2, 3, 4, 5]
# lookback_trade_days = [21, 42, 63, 84]
ma_exp = [0, 1, 2, 3, 5, 10]
# metric_r2_threshold = [0.0, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]
# regression_alpha = [1, 2, 4, 8, 16]
weight_exp = [0.0, 0.25, 0.5, 1.0, 2.0, 4.0]
