title = "趋势增强"
description = "持有趋势增强得分最高的ETF"

tickers = [
  "510300", # 沪深300ETF
  "510500", # 中证500ETF
  "159949", # 创业板50ETF
  "510900", # 恒生H股ETF
  "512090", # MSCI中国A股ETF
  "515180", # 中证红利ETF
  "513100", # 纳斯达克100ETF
  "513500", # 标普500ETF
  "518880", # 黄金ETF
  "511260", # 十年国债ETF
  "511180", # 可转债ETF
  "516650", # 有色金属ETF
  "162411", # 华宝油气LOF
  "159985", # 豆粕ETF
]

[[rules]]
name = "hold_top_trend"
frequency = "1w"

[rules.options]
limit = 1
lookback_trade_days = 66
ma_exp = 20
ma_period_fast = 5
ma_period_slow = 20
regression_alpha = 8
regression_test = 0.3

[rules.search]
frequency = ["1w", "2w", "4w", "8w"]
limit = [1, 2, 3, 4, 5]
lookback_trade_days = [44, 66, 88]
ma_exp = [10, 20, 25]
# regression_alpha = [1, 2, 4, 8, 16]
# regression_test = [0.2, 0.3, 0.4]
